name: Build Java / Python dev releases

on: workflow_dispatch

jobs:
  get-version:
    name: Get version from gradle.properties
    uses: th2-net/.github/.github/workflows/compound-prebuild-java-dev-workflow.yml@main
  python-scan:
    name: Vulnerabilities scan
    uses: th2-net/.github/.github/workflows/python-scan.yml@main
  build-java:
    uses: th2-net/.github/.github/workflows/compound-java.yml@main
    needs: [ python-scan ]
    with:
      build-target: 'Sonatype'
      devRelease: true
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
      nvd-api-key: ${{ secrets.NVD_APIKEY }}
      cisa-domain: ${{ secrets.CISA_DOMAIN }}
      cisa-user: ${{ secrets.CISA_USER }}
      cisa-password: ${{ secrets.CISA_PWD }}
  build-python:
    name: Dev build and Python distributions to PyPI
    needs: [ get-version, python-scan ]
    uses: th2-net/.github/.github/workflows/compaund-python-grpc-pypi-publication.yml@main
    with:
      custom-version: ${{ needs.get-version.outputs.versionNumber }}rc1
    secrets:
      pypi_password: ${{ secrets.PYPI_PASSWORD }}