name: test

on:
  push:
    branches-ignore:
      - master
      - version-*
    paths-ignore:
      - README.md

jobs:
  build:
    uses: th2-net/.github/.github/workflows/compound-grpc.yml@compound-grpc # FIXME: revert to main
    with:
      build-mode: snapshot