name: test

on:
  push:
    branches-ignore:
      - master
      - version-*
    paths-ignore:
      - README.md

jobs:
  get-python:
    uses: th2-net/.github/.github/workflows/python-prepare-version.yml@compound-grpc # FIXME: revert to main
#  build:
#    uses: th2-net/.github/.github/workflows/compound-grpc.yml@compound-grpc # FIXME: revert to main
#    with:
#      build-mode: snapshot